//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naidis_TARpe24.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Naidis_TARpe24.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muuda keelt.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-performance system language .
        /// </summary>
        public static string CPlusDesc {
            get {
                return ResourceManager.GetString("CPlusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerful object-oriented language.
        /// </summary>
        public static string CSharpDesc {
            get {
                return ResourceManager.GetString("CSharpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnglishButton {
            get {
                return ResourceManager.GetString("EnglishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian.
        /// </summary>
        public static string EstonianButton {
            get {
                return ResourceManager.GetString("EstonianButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming portfolio  💻.
        /// </summary>
        public static string GreetingText {
            get {
                return ResourceManager.GetString("GreetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write once, run anywhere .
        /// </summary>
        public static string JavaDesc {
            get {
                return ResourceManager.GetString("JavaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language of the web.
        /// </summary>
        public static string JavaScriptDesc {
            get {
                return ResourceManager.GetString("JavaScriptDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great for data and automation.
        /// </summary>
        public static string PythonDesc {
            get {
                return ResourceManager.GetString("PythonDesc", resourceCulture);
            }
        }
    }
}
